<a href="https://colab.research.google.com/github/namanyadav2706/DataScience-Projects/blob/main/4_Password_Strength_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
import pandas as pd                                                    ## import the pandas library

In [ ]:
df=pd.read_csv('4_Password_Strength.csv',error_bad_lines=False)        ## read the dataset

In [54]:
df.head()

password  strength
0     kzde5577         1
1     kino3434         1
2    visi7k1yr         1
3     megzy123         1
4  lamborghin1         1

In [55]:
df=df.dropna()

In [56]:
df['strength']=df['strength'].map({0:"weak",1:"medium",2:"strong"})  ## change 0--> weak , 1--> medium & 2--> strong in the dataset

In [57]:
df.head()

password strength
0     kzde5577   medium
1     kino3434   medium
2    visi7k1yr   medium
3     megzy123   medium
4  lamborghin1   medium

In [58]:
def toList(password):        ## function to convert password into the list eg. 'india' --> ['i','n','d','i','a']
    char=[]
    for i in password:
        char.append(i)
    return char

In [60]:
import numpy as np
x=np.array(df["password"])  ## Independent feature
y=np.array(df["strength"])  ## Dependent feature

In [62]:
from sklearn.feature_extraction.text import TfidfVectorizer  ## creating the bag of characters to find the combination of characters
tidf=TfidfVectorizer(tokenizer=toList)
x=tidf.fit_transform(x)

In [64]:
from sklearn.model_selection import train_test_split         ## splitting the dataset into test set and train set
X_train,X_test, y_train,  y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [66]:
from sklearn.ensemble import RandomForestClassifier  ## creating the classification model
classifier=RandomForestClassifier()
classifier.fit(X_train,y_train)

RandomForestClassifier()

In [73]:
y_pred=classifier.predict(X_test)                   ## predicting the test values

In [75]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)                  ## creating the confusion matrix
print(cm)
acc=accuracy_score(y_test,y_pred)                   ## checking the accuracy score
print(acc)

[[97923   581   547]
 [ 1599 15284    28]
 [ 3285     4 14677]]
0.9548712741174362


In [81]:
import getpass                                     ## this module is used to take passwords input in python

pswrd=getpass.getpass('enter the password')        ## taking the input and predicting the results
pswrd=tidf.transform([pswrd]).toarray()
print(classifier.predict(pswrd))                   ## printing the prediction

enter the password··········
['weak']


Resourses & Info:

getpass module: https://www.geeksforgeeks.org/python-getpass-module/

TF-IDF: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html

